# Generated by Django 4.1.3 on 2022-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('productcode', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
