# Generated by Django 4.1.3 on 2022-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('productcode', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('paymentcode', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
