# Generated by Django 4.1.3 on 2022-11-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
